### ISSUE TITLE
Add ChainTip word logo and icon to this repository

### ISSUE THREAD

**Issue by chaintip** [chaintip/chaintip-design#1]
@MrSmooshy, this one's for you.

**Comment by tea-spoon** [comment]
@chaintip

**Comment by chaintip** [comment]
`0.0136435 BCH`| `~  20.03 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4dre9957z6falphsgx3cpv9t9lkuw0szn7c7) to this issue by @tea-spoon.
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/8), get a pull request merged with ```@chaintip fixes #1``` in the creation comment.

**Comment by chaintip** [comment]
`0.0136435 BCH`| `~  21.05 USD` has now been claimed by @MrSmooshy when pull request [#3](http://github.chaintip.org/chaintip/chaintip-design/pull/3) was merged. This will be sent to your wallet once you link it with chaintip.
